name: run codefresh pipeline
on: push
jobs:
  codefresh:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: 'run pipeline'
        uses: codefresh-io/codefresh-pipeline-runner@v6
        env:
          PIPELINE_NAME: 'sobakaka/sobakaka'
          TRIGGER_NAME: 'dsomeone/sobakaka'
          CF_API_KEY: 5f6797b9358a65768162c9a1.ef0235047bb7190cff92bd86f4ff3f30
        id: run-pipeline

      - name: 'run pipeline1'
        uses: codefresh-io/codefresh-pipeline-runner@v6
        env:
          PIPELINE_NAME: 'default/MyPipeline'
          TRIGGER_NAME: 'dsomeone/sobakaka'
          CF_API_KEY: 5f6797b9358a65768162c9a1.ef0235047bb7190cff92bd86f4ff3f30
        id: run-pipeline1
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dsomeone
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./monero/cpu
          file: ./monero/cpu/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: dsomeone/nizadam:latest
